#ifdef _MSC_VER
#include "stdafx.h"
#endif

#include "cal_eeprom.h"

int main() {

    std::unordered_map<float, packet_struct> calibration_map;
    InitCalMap(calibration_map);
    std::cout << "Calibration Data written to file" << std::endl;
    DisplayCalMap(calibration_map);

    char file_name[120] = "calibration_map.bin";
    SaveCalMap(calibration_map, file_name);

    std::cout << std::endl
              << "Calibration Data read from file generated by Python is"
              << std::endl;
    char read_file_name[120] = "calibration_map.bin";
    std::unordered_map<float, packet_struct> read_calibration_map;
    ReadCalMap(read_calibration_map, read_file_name);
    DisplayCalMap(read_calibration_map);

    return 0;
}
