name: py36tofcalib
channels:
- conda-forge
- defaults
dependencies:
- click=7.0
- ipython=7.2.0
- jupyter=1.0.0
- mpld3=0.3
- natsort=5.5.0
- numpy=1.15.4
- opencv=3.4.1
- pandas=0.24.1
- pip=19.0.1
- pybind11=2.2.4
- pyserial=3.4
- python=3.6.8
- scipy=1.2.1
- seaborn=0.9.0
- bokeh=1.1.0