#ifndef __TOF_ISP_TABLE_H__
#define __TOF_ISP_TABLE_H__

#include <stdint.h>

/**************************************************************************************
 * the numbers in each arrays shown below that are corresponding to target registers
 **************************************************************************************/
typedef enum _eISP_REG_CMN{
	ISP_REG_CMN_SHD_OFST0=0,
	ISP_REG_CMN_SHD_OFST1,
	ISP_REG_CMN_SHD_OFST2,
	ISP_REG_CMN_SHD_OFST3,
	ISP_REG_CMN_SHD_OFST4,
	ISP_REG_CMN_SHD_OFST5,
	ISP_REG_CMN_SHD_OFST6,
	ISP_REG_CMN_SHD_OFST7,
	ISP_REG_CMN_SHD_OFST8,
	ISP_REG_CMN_SHD_OFST9,
	ISP_REG_CMN_SHD_OFST10,
	ISP_REG_CMN_SHD_OFST11,
	ISP_REG_CMN_SHD_OFST12,
	ISP_REG_CMN_SHD_OFST13,
	ISP_REG_CMN_SHD_OFST14,
	ISP_REG_CMN_SHD_OFST15,
	ISP_REG_CMN_SHD_OFST16,
	ISP_REG_CMN_SHD_OFST17,
	ISP_REG_CMN_SHD_OFST18,
	ISP_REG_CMN_SHD_OFST19,
	ISP_REG_CMN_SHD_OFST20,
	ISP_REG_CMN_SHD_OFST21,
	ISP_REG_CMN_SHD_OFST22,
	ISP_REG_CMN_SHD_OFST23,
	ISP_REG_CMN_SHD_OFST24,
	ISP_REG_CMN_SHD_OFST25,
	ISP_REG_CMN_SHD_OFST26,
	ISP_REG_CMN_SHD_OFST27,
	ISP_REG_CMN_SHD_OFST28,
	ISP_REG_CMN_SHD_OFST29,
	ISP_REG_CMN_SHD_OFST30,
	ISP_REG_CMN_SHD_OFST31,
	ISP_REG_CMN_SHD_OFST32,
	ISP_REG_CMN_SHD_OFST33,
	ISP_REG_CMN_SHD_OFST34,
	ISP_REG_CMN_SHD_OFST35,
	ISP_REG_CMN_SHD_OFST36,
	ISP_REG_CMN_SHD_OFST37,
	ISP_REG_CMN_SHD_OFST38,
	ISP_REG_CMN_SHD_OFST39,
	ISP_REG_CMN_SHD_OFST40,
	ISP_REG_CMN_SHD_OFST41,
	ISP_REG_CMN_SHD_OFST42,
	ISP_REG_CMN_SHD_OFST43,
	ISP_REG_CMN_SHD_OFST44,
	ISP_REG_CMN_SHD_OFST45,
	ISP_REG_CMN_SHD_OFST46,
	ISP_REG_CMN_SHD_OFST47,
	ISP_REG_CMN_SHD_OFST48,
	ISP_REG_CMN_SHD_OFST49,
	ISP_REG_CMN_SHD_OFST50,
	ISP_REG_CMN_SHD_OFST51,
	ISP_REG_CMN_SHD_OFST52,
	ISP_REG_CMN_SHD_OFST53,
	ISP_REG_CMN_SHD_OFST54,
	ISP_REG_CMN_SHD_OFST55,
	ISP_REG_CMN_SHD_OFST56,
	ISP_REG_CMN_SHD_OFST57,
	ISP_REG_CMN_SHD_OFST58,
	ISP_REG_CMN_SHD_OFST59,
	ISP_REG_CMN_SHD_OFST60,
	ISP_REG_CMN_SHD_OFST61,
	ISP_REG_CMN_SHD_OFST62,
	ISP_REG_CMN_SHD_OFST63,
	ISP_REG_CMN_SHD_OFST64,
	ISP_REG_CMN_SHD_OFST65,
	ISP_REG_CMN_SHD_OFST66,
	ISP_REG_CMN_SHD_OFST67,
	ISP_REG_CMN_SHD_OFST68,
	ISP_REG_CMN_SHD_OFST69,
	ISP_REG_CMN_SHD_OFST70,
	ISP_REG_CMN_SHD_OFST71,
	ISP_REG_CMN_SHD_OFST72,
	ISP_REG_CMN_SHD_OFST73,
	ISP_REG_CMN_SHD_OFST74,
	ISP_REG_CMN_SHD_OFST75,
	ISP_REG_CMN_SHD_OFST76,
	ISP_REG_CMN_SHD_OFST77,
	ISP_REG_CMN_SHD_OFST78,
	ISP_REG_CMN_SHD_OFST79,
	ISP_REG_CMN_SHD_OFST80,
	ISP_REG_CMN_SHD_OFST81,
	ISP_REG_CMN_SHD_OFST82,
	ISP_REG_CMN_SHD_OFST83,
	ISP_REG_CMN_SHD_OFST84,
	ISP_REG_CMN_SHD_OFST85,
	ISP_REG_CMN_SHD_OFST86,
	ISP_REG_CMN_SHD_OFST87,
	ISP_REG_CMN_SHD_OFST88,
	ISP_REG_CMN_SHD_OFST89,
	ISP_REG_CMN_SHD_OFST90,
	ISP_REG_CMN_SHD_OFST91,
	ISP_REG_CMN_SHD_OFST92,
	ISP_REG_CMN_SHD_OFST93,
	ISP_REG_CMN_SHD_OFST94,
	ISP_REG_CMN_SHD_OFST95,
	ISP_REG_CMN_SHD_OFST96,
	ISP_REG_CMN_SHD_OFST97,
	ISP_REG_CMN_SHD_OFST98,
	ISP_REG_CMN_SHD_OFST99,
	ISP_REG_CMN_SHD_OFST100,
	ISP_REG_CMN_SHD_OFST101,
	ISP_REG_CMN_SHD_OFST102,
	ISP_REG_CMN_SHD_OFST103,
	ISP_REG_CMN_SHD_OFST104,
	ISP_REG_CMN_SHD_OFST105,
	ISP_REG_CMN_SHD_OFST106,
	ISP_REG_CMN_SHD_OFST107,
	ISP_REG_CMN_SHD_OFST108,
	ISP_REG_CMN_SHD_OFST109,
	ISP_REG_CMN_SHD_OFST110,
	ISP_REG_CMN_SHD_OFST111,
	ISP_REG_CMN_SHD_OFST112,
	ISP_REG_CMN_SHD_OFST113,
	ISP_REG_CMN_SHD_OFST114,
	ISP_REG_CMN_SHD_OFST115,
	ISP_REG_CMN_SHD_OFST116,
	ISP_REG_CMN_SHD_OFST117,
	ISP_REG_CMN_SHD_OFST118,
	ISP_REG_CMN_SHD_OFST119,
	ISP_REG_CMN_SHD_OFST120,
	ISP_REG_CMN_SHD_OFST121,
	ISP_REG_CMN_SHD_OFST122,
	ISP_REG_CMN_SHD_OFST123,
	ISP_REG_CMN_SHD_OFST124,
	ISP_REG_CMN_SHD_OFST125,
	ISP_REG_CMN_SHD_OFST126,
	ISP_REG_CMN_SHD_OFST127,
	ISP_REG_CMN_SHD_OFST128,
	ISP_REG_CMN_SHD_OFST129,
	ISP_REG_CMN_SHD_OFST130,
	ISP_REG_CMN_SHD_OFST131,
	ISP_REG_CMN_SHD_OFST132,
	ISP_REG_CMN_SHD_OFST133,
	ISP_REG_CMN_SHD_OFST134,
	ISP_REG_CMN_SHD_OFST135,
	ISP_REG_CMN_SHD_OFST136,
	ISP_REG_CMN_SHD_OFST137,
	ISP_REG_CMN_SHD_OFST138,
	ISP_REG_CMN_SHD_OFST139,
	ISP_REG_CMN_SHD_OFST140,
	ISP_REG_CMN_SHD_OFST141,
	ISP_REG_CMN_SHD_OFST142,
	ISP_REG_CMN_SHD_OFST143,
	ISP_REG_CMN_SHD_OFST144,
	ISP_REG_CMN_SHD_OFST145,
	ISP_REG_CMN_SHD_OFST146,
	ISP_REG_CMN_SHD_OFST147,
	ISP_REG_CMN_SHD_OFST148,
	ISP_REG_CMN_SHD_OFST149,
	ISP_REG_CMN_SHD_OFST150,
	ISP_REG_CMN_SHD_OFST151,
	ISP_REG_CMN_SHD_OFST152,
	ISP_REG_CMN_SHD_OFST153,
	ISP_REG_CMN_SHD_OFST154,
	ISP_REG_CMN_SHD_OFST155,
	ISP_REG_CMN_SHD_OFST156,
	ISP_REG_CMN_SHD_OFST157,
	ISP_REG_CMN_SHD_OFST158,
	ISP_REG_CMN_SHD_OFST159,
	ISP_REG_CMN_SHD_OFST160,
	ISP_REG_CMN_SHD_OFST161,
	ISP_REG_CMN_SHD_OFST162,
	ISP_REG_CMN_SHD_OFST163,
	ISP_REG_CMN_SHD_OFST164,
	ISP_REG_CMN_SHD_OFST165,
	ISP_REG_CMN_SHD_OFST166,
	ISP_REG_CMN_SHD_OFST167,
	ISP_REG_CMN_SHD_OFST168,
	ISP_REG_CMN_SHD_OFST169,
	ISP_REG_CMN_SHD_OFST170,
	ISP_REG_CMN_SHD_OFST171,
	ISP_REG_CMN_SHD_OFST172,
	ISP_REG_CMN_SHD_OFST173,
	ISP_REG_CMN_SHD_OFST174,
	ISP_REG_CMN_SHD_OFST175,
	ISP_REG_CMN_SHD_OFST176,
	ISP_REG_CMN_SHD_OFST177,
	ISP_REG_CMN_SHD_OFST178,
	ISP_REG_CMN_SHD_OFST179,
	ISP_REG_CMN_SHD_OFST180,
	ISP_REG_CMN_SHD_OFST181,
	ISP_REG_CMN_SHD_OFST182,
	ISP_REG_CMN_SHD_OFST183,
	ISP_REG_CMN_SHD_OFST184,
	ISP_REG_CMN_SHD_OFST185,
	ISP_REG_CMN_SHD_OFST186,
	ISP_REG_CMN_SHD_OFST187,
	ISP_REG_CMN_SHD_OFST188,
	ISP_REG_CMN_SHD_OFST189,
	ISP_REG_CMN_SHD_OFST190,
	ISP_REG_CMN_SHD_OFST191,
	ISP_REG_CMN_SHD,
	ISP_REG_CMN_SHD_X0,
	ISP_REG_CMN_SHD_XPWR0,
	ISP_REG_CMN_SHD_XPWR1,
	ISP_REG_CMN_SHD_XPWR2,
	ISP_REG_CMN_SHD_XPWR3,
	ISP_REG_CMN_SHD_Y0,
	ISP_REG_CMN_SHD_YPWR0,
	ISP_REG_CMN_SHD_YPWR1,
	ISP_REG_CMN_SHD_YPWR2,
	ISP_REG_CMN_DFCT_PIX_TH_TBL0,
	ISP_REG_CMN_DFCT_PIX_TH_TBL1,
	ISP_REG_CMN_DFCT_PIX_TH_TBL2,
	ISP_REG_CMN_DFCT_PIX_TH_TBL3,
	ISP_REG_CMN_DFCT_PIX_TH_TBL4,
	ISP_REG_CMN_DFCT_PIX_TH_TBL5,
	ISP_REG_CMN_DFCT_PIX_TH_TBL6,
	ISP_REG_CMN_DFCT_PIX_TH_TBL7,
	ISP_REG_CMN_DFCT_PIX_TH_TBL8,
	ISP_REG_CMN_DFCT_PIX_TH_TBL9,
	ISP_REG_CMN_DFCT_PIX_TH_TBL10,
	ISP_REG_CMN_DFCT_PIX_TH_TBL11,
	ISP_REG_CMN_DFCT0,
	ISP_REG_CMN_DFCT1,
	ISP_REG_CMN_SHP_LOC,
	ISP_REG_CMN_SHD_LOC,
	ISP_REG_CMN_OUTPUT,
	ISP_REG_CMN_OUTPUTSEL,
	ISP_REG_CMN_VC,
	ISP_REG_CMN_GRID3,
	ISP_REG_CMN_IR1,
	ISP_REG_CMN_IR_GMM0,
	ISP_REG_CMN_IR_GMM1,
	ISP_REG_CMN_IR_GMM2,
	ISP_REG_CMN_IR_GMM_Y0,
	ISP_REG_CMN_IR_GMM_Y1,
	ISP_REG_CMN_IR_GMM_Y2,
	ISP_REG_CMN_IR_GMM_Y3,
	ISP_REG_CMN_IR_GMM_Y4,
	ISP_REG_CMN_IR_GMM_Y5,
	ISP_REG_CMN_IR_GMM_Y6,
	ISP_REG_CMN_IR_GMM_Y7,
	ISP_REG_CMN_IR_GMM_Y8,
	ISP_REG_CMN_CHKR_UPPRTH,
	ISP_REG_CMN_CHKR_LWRTH,
	ISP_REG_CMN_CHKR_START_V,
	ISP_REG_CMN_CHKR_START_H,
	ISP_REG_CMN_CHKR_SIZE_H,
	ISP_REG_CMN_CHKR_UPPRERR_H,
	ISP_REG_CMN_CHKR_UPPRERR_V,
	ISP_REG_CMN_CHKR_LWRERR_H,
	ISP_REG_CMN_CHKR_LWRERR_V,
	ISP_REG_CMN_CHKR_DET_ENA,

	ISP_REG_CMN_MAX
}eISP_REG_CMN;

typedef enum _eISP_REG_MODE{
	ISP_REG_MODE_LNR_OFST00=0,
	ISP_REG_MODE_LNR_OFST01,
	ISP_REG_MODE_LNR_OFST02,
	ISP_REG_MODE_LNR_OFST03,
	ISP_REG_MODE_LNR_OFST04,
	ISP_REG_MODE_LNR_OFST05,
	ISP_REG_MODE_LNR_OFST06,
	ISP_REG_MODE_LNR_OFST07,
	ISP_REG_MODE_LNR_OFST08,
	ISP_REG_MODE_LNR_OFST09,
	ISP_REG_MODE_LNR_OFST10,
	ISP_REG_MODE_LNR_OFST11,
	ISP_REG_MODE_LNR_OFST12,
	ISP_REG_MODE_LNR_OFST13,
	ISP_REG_MODE_LNR_OFST14,
	ISP_REG_MODE_LNR_OFST15,
	ISP_REG_MODE_LNR_OFST16,
	ISP_REG_MODE_LNR_OFST17,
	ISP_REG_MODE_LNR_OFST18,
	ISP_REG_MODE_LNR_OFST19,
	ISP_REG_MODE_LNR_OFST20,
	ISP_REG_MODE_LNR_OFST21,
	ISP_REG_MODE_LNR_OFST22,
	ISP_REG_MODE_LNR_OFST23,
	ISP_REG_MODE_LNR_OFST24,
	ISP_REG_MODE_LNR_OFST25,
	ISP_REG_MODE_LNR_OFST26,
	ISP_REG_MODE_LNR_OFST27,
	ISP_REG_MODE_LNR_OFST28,
	ISP_REG_MODE_LNR_OFST29,
	ISP_REG_MODE_LNR_OFST30,
	ISP_REG_MODE_LNR_OFST31,
	ISP_REG_MODE_LNR_OFST32,
	ISP_REG_MODE_LNR_OFST33,
	ISP_REG_MODE_LNR_OFST34,
	ISP_REG_MODE_LNR_OFST35,
	ISP_REG_MODE_LNR_OFST36,
	ISP_REG_MODE_LNR_OFST37,
	ISP_REG_MODE_LNR_OFST38,
	ISP_REG_MODE_LNR_OFST39,
	ISP_REG_MODE_LNR_OFST40,
	ISP_REG_MODE_LNR_OFST41,
	ISP_REG_MODE_LNR_OFST42,
	ISP_REG_MODE_LNR_OFST43,
	ISP_REG_MODE_LNR_OFST44,
	ISP_REG_MODE_LNR_OFST45,
	ISP_REG_MODE_LNR_OFST46,
	ISP_REG_MODE_LNR_OFST47,
	ISP_REG_MODE_LNR_OFST48,
	ISP_REG_MODE_LNR_X0,
	ISP_REG_MODE_LNR_XPWR_01,
	ISP_REG_MODE_LNR_XPWR_05,
	ISP_REG_MODE_LNR_XPWR_09,
	ISP_REG_MODE_LNR_XPWR_13,
	ISP_REG_MODE_LNR_XPWR_17,
	ISP_REG_MODE_LNR_XPWR_21,
	ISP_REG_MODE_LNR_XPWR_25,
	ISP_REG_MODE_LNR_XPWR_29,
	ISP_REG_MODE_LNR_XPWR_33,
	ISP_REG_MODE_LNR_XPWR_37,
	ISP_REG_MODE_LNR_XPWR_41,
	ISP_REG_MODE_LNR_XPWR_45,
	ISP_REG_MODE_DEPTH_OFST,
	ISP_REG_MODE_DEPTH_EX_OFST,
	ISP_REG_MODE_DEPTH_SLOPE,
	ISP_REG_MODE_RATE_ADJST0,
	ISP_REG_MODE_RATE_ADJST1,
	ISP_REG_MODE_RATE_ADJST2,
	ISP_REG_MODE_ALIGN0,
	ISP_REG_MODE_ALIGN1,
	ISP_REG_MODE_ALIGN2,
	ISP_REG_MODE_ALIGN3,
	ISP_REG_MODE_ALIGN4,
	ISP_REG_MODE_ALIGN5,
	ISP_REG_MODE_ALIGN6,
	ISP_REG_MODE_ALIGN7,
	ISP_REG_MODE_ALIGN8,
	ISP_REG_MODE_ALIGN9,
	ISP_REG_MODE_ALIGN10,
	ISP_REG_MODE_READ_SIZE0,
	ISP_REG_MODE_READ_SIZE1,
	ISP_REG_MODE_READ_SIZE3,
	ISP_REG_MODE_READ_SIZE4,
	ISP_REG_MODE_READ_SIZE5,
	ISP_REG_MODE_READ_SIZE6,
	ISP_REG_MODE_READ_SIZE7,
	ISP_REG_MODE_ROI0,
	ISP_REG_MODE_ROI1,
	ISP_REG_MODE_ROI2,
	ISP_REG_MODE_ROI3,
	ISP_REG_MODE_ROI4,
	ISP_REG_MODE_ROI5,
	ISP_REG_MODE_ROI6,
	ISP_REG_MODE_ROI7,
	ISP_REG_MODE_IR_LNR12_SW,
	ISP_REG_MODE_GRID0,
	ISP_REG_MODE_GRID1,
	ISP_REG_MODE_GRID2,
	ISP_REG_MODE_RAWNR_XPWR_1,
	ISP_REG_MODE_RAWNR_XPWR_5,
	ISP_REG_MODE_RAWNR_XPWR_9,
	ISP_REG_MODE_RAWNR_BL_TBL00,
	ISP_REG_MODE_RAWNR_BL_TBL01,
	ISP_REG_MODE_RAWNR_BL_TBL02,
	ISP_REG_MODE_RAWNR_BL_TBL03,
	ISP_REG_MODE_RAWNR_BL_TBL04,
	ISP_REG_MODE_RAWNR_BL_TBL05,
	ISP_REG_MODE_RAWNR_BL_TBL06,
	ISP_REG_MODE_RAWNR_BL_TBL07,
	ISP_REG_MODE_RAWNR_BL_TBL08,
	ISP_REG_MODE_RAWNR_BL_TBL09,
	ISP_REG_MODE_RAWNR_BL_TBL10,
	ISP_REG_MODE_RAWNR_BL_TBL11,
	ISP_REG_MODE_RAWNR_BL_TBL12,
	ISP_REG_MODE_RAWNR_MED,
	ISP_REG_MODE_RAWNR_SAT_TH,
	ISP_REG_MODE_RAWNR_BK_TBL00,
	ISP_REG_MODE_RAWNR_BK_TBL01,
	ISP_REG_MODE_RAWNR_BK_TBL02,
	ISP_REG_MODE_RAWNR_BK_TBL03,
	ISP_REG_MODE_RAWNR_BK_TBL04,
	ISP_REG_MODE_RAWNR_BK_TBL05,
	ISP_REG_MODE_RAWNR_BK_TBL06,
	ISP_REG_MODE_RAWNR_BK_TBL07,
	ISP_REG_MODE_RAWNR_BK_TBL08,
	ISP_REG_MODE_RAWNR_BK_TBL09,
	ISP_REG_MODE_RAWNR_BK_TBL10,
	ISP_REG_MODE_RAWNR_BK_TBL11,
	ISP_REG_MODE_RAWNR_BK_TBL12,
	ISP_REG_MODE_COR0,
	ISP_REG_MODE_COR1,
	ISP_REG_MODE_COR2,
	ISP_REG_MODE_CORB0,
	ISP_REG_MODE_CORB1,
	ISP_REG_MODE_CORB2,
	ISP_REG_MODE_CORF0,
	ISP_REG_MODE_CORF1,
	ISP_REG_MODE_CORF2,
	ISP_REG_MODE_IR_ENABLED_COR,
	ISP_REG_MODE_DEPTH1,
	ISP_REG_MODE_CONTROL,
	ISP_REG_MODE_PLS_MOD_CTRL,
	ISP_REG_MODE_PLS_MOD_VAL0,
	ISP_REG_MODE_PLS_MOD_VAL1,
	ISP_REG_MODE_PLS_MOD_VAL2,
	ISP_REG_MODE_PLS_MOD_VAL3,
	ISP_REG_MODE_PLS_MOD_VAL4,
	ISP_REG_MODE_PLS_MOD_VAL5,
	ISP_REG_MODE_PLS_MOD_VAL6,
	ISP_REG_MODE_PLS_MOD_VAL7,
	ISP_REG_MODE_PLS_MOD_VAL8,
	ISP_REG_MODE_PLS_MOD_VAL9,
	ISP_REG_MODE_DEPTH_ALF_GAIN,
	ISP_REG_MODE_DEPTH_ALF_OFST,
	ISP_REG_MODE_DPTHDET_START_H,
	ISP_REG_MODE_DPTHDET_START_V,
	ISP_REG_MODE_DPTHDET_SIZE_H,
	ISP_REG_MODE_DPTHDET_SIZE_V,

	ISP_REG_MODE_MAX
}eISP_REG_MODE;


typedef enum _eISP_RAM_MODE{
	ISP_RAM_MODE_EXP_ADR_NUM,
	ISP_RAM_MODE_EXP_ADR_LONG1,
	ISP_RAM_MODE_EXP_ADR_LONG2,
	ISP_RAM_MODE_EXP_ADR_LONG3,
	ISP_RAM_MODE_EXP_ADR_LONG4,
	ISP_RAM_MODE_EXP_ADR_LONG5,
	ISP_RAM_MODE_EXP_ADR_LONG6,
	ISP_RAM_MODE_EXP_ADR_LONG7,
	ISP_RAM_MODE_EXP_ADR_LONG8,
	ISP_RAM_MODE_EXP_ADR_LONG9,
	ISP_RAM_MODE_EXP_ADR_LONG10,
	ISP_RAM_MODE_EXP_ADR_LONG11,
	ISP_RAM_MODE_EXP_ADR_LONG12,
	ISP_RAM_MODE_EXP_ADR_LONG13,
	ISP_RAM_MODE_EXP_ADR_LONG14,
	ISP_RAM_MODE_EXP_ADR_LONG15,
	ISP_RAM_MODE_EXP_ADR_SHORT1,
	ISP_RAM_MODE_EXP_ADR_SHORT2,
	ISP_RAM_MODE_EXP_ADR_SHORT3,
	ISP_RAM_MODE_EXP_ADR_SHORT4,
	ISP_RAM_MODE_EXP_ADR_LMS1,
	ISP_RAM_MODE_EXP_ADR_LMS2,
	ISP_RAM_MODE_EXP_ADR_LMS3,
	ISP_RAM_MODE_EXP_ADR_LMS4,
	ISP_RAM_MODE_DMMY_TRNS_NUM,
	ISP_RAM_MODE_DMMY_TRNS_ADR1,
	ISP_RAM_MODE_DMMY_TRNS_ADR2,
	ISP_RAM_MODE_DMMY_TRNS_ADR3,
	ISP_RAM_MODE_DMMY_TRNS_ADR4,
	ISP_RAM_MODE_VD_INI_OFST_ADR_NUM,
	ISP_RAM_MODE_VD_INIT_OFST_ADR1,
	ISP_RAM_MODE_VD_INIT_OFST_ADR2,
	ISP_RAM_MODE_VD_INIT_OFST_ADR3,
	ISP_RAM_MODE_VD_INIT_OFST_ADR4,
	ISP_RAM_MODE_VD_REG_ADR,
	ISP_RAM_MODE_PHASE_ADR_NUM,
	ISP_RAM_MODE_PHASE_SUB_1,
	ISP_RAM_MODE_PHASE_SUB_2,
	ISP_RAM_MODE_PHASE_SUB_3,
	ISP_RAM_MODE_PHASE_SUB_4,
	ISP_RAM_MODE_PHASE_SUB_5,
	ISP_RAM_MODE_PHASE_SUB_6,
	ISP_RAM_MODE_PHASE_SUB_7,
	ISP_RAM_MODE_PHASE_SUB_8,
	ISP_RAM_MODE_PHASE_A0_1,
	ISP_RAM_MODE_PHASE_A0_2,
	ISP_RAM_MODE_PHASE_A0_3,
	ISP_RAM_MODE_PHASE_A0_4,
	ISP_RAM_MODE_PHASE_A0_5,
	ISP_RAM_MODE_PHASE_A0_6,
	ISP_RAM_MODE_PHASE_A0_7,
	ISP_RAM_MODE_PHASE_A0_8,
	ISP_RAM_MODE_PHASE_A1_1,
	ISP_RAM_MODE_PHASE_A1_2,
	ISP_RAM_MODE_PHASE_A1_3,
	ISP_RAM_MODE_PHASE_A1_4,
	ISP_RAM_MODE_PHASE_A1_5,
	ISP_RAM_MODE_PHASE_A1_6,
	ISP_RAM_MODE_PHASE_A1_7,
	ISP_RAM_MODE_PHASE_A1_8,
	ISP_RAM_MODE_PHASE_A2_1,
	ISP_RAM_MODE_PHASE_A2_2,
	ISP_RAM_MODE_PHASE_A2_3,
	ISP_RAM_MODE_PHASE_A2_4,
	ISP_RAM_MODE_PHASE_A2_5,
	ISP_RAM_MODE_PHASE_A2_6,
	ISP_RAM_MODE_PHASE_A2_7,
	ISP_RAM_MODE_PHASE_A2_8,
	ISP_RAM_MODE_IDLE_PERI_NUM,
	ISP_RAM_MODE_IDLE_PERI_ADR1,
	ISP_RAM_MODE_IDLE_PERI_ADR2,
	ISP_RAM_MODE_IDLE_PERI_ADR3,
	ISP_RAM_MODE_IDLE_PERI_ADR4,

	ISP_RAM_MODE_MAX
}eISP_RAM_MODE;



/**************************************************************************************
 * CS Control variables
 **************************************************************************************/
typedef enum _eCTRL_CMN{
	CTRL_CMN_CAM_MODEL_NAME_0,
	CTRL_CMN_CAM_MODEL_NAME_1,
	CTRL_CMN_CAM_MODEL_NAME_2,
	CTRL_CMN_CAM_MODEL_NAME_3,
	CTRL_CMN_CAM_MODEL_NAME_4,
	CTRL_CMN_CAM_MODEL_NAME_5,
	CTRL_CMN_CAM_MODEL_NAME_6,
	CTRL_CMN_CAM_MODEL_NAME_7,
	CTRL_CMN_CAM_MODEL_NAME_8,
	CTRL_CMN_CAM_MODEL_NAME_9,
	CTRL_CMN_CAM_MODEL_NAME_10,
	CTRL_CMN_CAM_MODEL_NAME_11,
	CTRL_CMN_CAM_MODEL_NAME_12,
	CTRL_CMN_CAM_MODEL_NAME_13,
	CTRL_CMN_CAM_MODEL_NAME_14,
	CTRL_CMN_CAM_MODEL_NAME_15,
	CTRL_CMN_CS_MODEL_NAME_0,
	CTRL_CMN_CS_MODEL_NAME_1,
	CTRL_CMN_CS_MODEL_NAME_2,
	CTRL_CMN_CS_MODEL_NAME_3,
	CTRL_CMN_CS_MODEL_NAME_4,
	CTRL_CMN_CS_MODEL_NAME_5,
	CTRL_CMN_CS_MODEL_NAME_6,
	CTRL_CMN_CS_MODEL_NAME_7,
	CTRL_CMN_CS_MODEL_NAME_8,
	CTRL_CMN_CS_MODEL_NAME_9,
	CTRL_CMN_CS_MODEL_NAME_10,
	CTRL_CMN_CS_MODEL_NAME_11,
	CTRL_CMN_CS_MODEL_NAME_12,
	CTRL_CMN_CS_MODEL_NAME_13,
	CTRL_CMN_CS_MODEL_NAME_14,
	CTRL_CMN_CS_MODEL_NAME_15,
	CTRL_CMN_TOFIS_MODEL_NAME_0,
	CTRL_CMN_TOFIS_MODEL_NAME_1,
	CTRL_CMN_TOFIS_MODEL_NAME_2,
	CTRL_CMN_TOFIS_MODEL_NAME_3,
	CTRL_CMN_TOFIS_MODEL_NAME_4,
	CTRL_CMN_TOFIS_MODEL_NAME_5,
	CTRL_CMN_TOFIS_MODEL_NAME_6,
	CTRL_CMN_TOFIS_MODEL_NAME_7,
	CTRL_CMN_TOFIS_MODEL_NAME_8,
	CTRL_CMN_TOFIS_MODEL_NAME_9,
	CTRL_CMN_TOFIS_MODEL_NAME_10,
	CTRL_CMN_TOFIS_MODEL_NAME_11,
	CTRL_CMN_TOFIS_MODEL_NAME_12,
	CTRL_CMN_TOFIS_MODEL_NAME_13,
	CTRL_CMN_TOFIS_MODEL_NAME_14,
	CTRL_CMN_TOFIS_MODEL_NAME_15,
	CTRL_CMN_LENS_MODEL_NAME_0,
	CTRL_CMN_LENS_MODEL_NAME_1,
	CTRL_CMN_LENS_MODEL_NAME_2,
	CTRL_CMN_LENS_MODEL_NAME_3,
	CTRL_CMN_LENS_MODEL_NAME_4,
	CTRL_CMN_LENS_MODEL_NAME_5,
	CTRL_CMN_LENS_MODEL_NAME_6,
	CTRL_CMN_LENS_MODEL_NAME_7,
	CTRL_CMN_LENS_MODEL_NAME_8,
	CTRL_CMN_LENS_MODEL_NAME_9,
	CTRL_CMN_LENS_MODEL_NAME_10,
	CTRL_CMN_LENS_MODEL_NAME_11,
	CTRL_CMN_LENS_MODEL_NAME_12,
	CTRL_CMN_LENS_MODEL_NAME_13,
	CTRL_CMN_LENS_MODEL_NAME_14,
	CTRL_CMN_LENS_MODEL_NAME_15,
	CTRL_CMN_CAM_SER_NO,
	CTRL_CMN_MAP_VERSION,
	CTRL_CMN_EX_CAM_SER_NO,
	CTRL_CMN_CALIB_DATE,
	CTRL_CMN_CALIB_SER_NO,
	CTRL_CMN_CAM_TYPE_CODE1,
	CTRL_CMN_CAM_TYPE_CODE2,
	CTRL_CMN_CS_MCODE_ID,
	CTRL_CMN_OPT_AXIS_CNTR_H,
	CTRL_CMN_OPT_AXIS_CNTR_V,
	CTRL_CMN_OPT_AXIS_TILT_ANGL,
	CTRL_CMN_OPT_AXIS_PAN_ANGL,
	CTRL_CMN_LENS_FOV_H,
	CTRL_CMN_LENS_FOV_V,
	CTRL_CMN_PRLX_H_FRM_RGBIS,
	CTRL_CMN_PRLX_V_FRM_RGBIS,
	CTRL_CMN_TOFIS_PITCH,
	CTRL_CMN_FOCAL_LEN,
	CTRL_CMN_VALID_RANG_MODE,
	CTRL_CMN_DATA_PACK_STR,
	CTRL_CMN_TAL_MODE_FLAG,
	CTRL_CMN_CS_INI_CODE_SIZE,
	CTRL_CMN_CHECK_SUM,
	CTRL_CMN_DEPTH_PLNR_X3_0,
	CTRL_CMN_DEPTH_PLNR_X3_1,
	CTRL_CMN_DEPTH_PLNR_X3_2,
	CTRL_CMN_DEPTH_PLNR_X3_3,
	CTRL_CMN_DEPTH_PLNR_X2_0,
	CTRL_CMN_DEPTH_PLNR_X2_1,
	CTRL_CMN_DEPTH_PLNR_X2_2,
	CTRL_CMN_DEPTH_PLNR_X2_3,
	CTRL_CMN_DEPTH_PLNR_X1_0,
	CTRL_CMN_DEPTH_PLNR_X1_1,
	CTRL_CMN_DEPTH_PLNR_X1_2,
	CTRL_CMN_DEPTH_PLNR_X1_3,
	CTRL_CMN_DEPTH_PLNR_X0_0,
	CTRL_CMN_DEPTH_PLNR_X0_1,
	CTRL_CMN_DEPTH_PLNR_X0_2,
	CTRL_CMN_DEPTH_PLNR_X0_3,
	CTRL_CMN_LENS_UNDIS_X3_0,
	CTRL_CMN_LENS_UNDIS_X3_1,
	CTRL_CMN_LENS_UNDIS_X3_2,
	CTRL_CMN_LENS_UNDIS_X3_3,
	CTRL_CMN_LENS_UNDIS_X2_0,
	CTRL_CMN_LENS_UNDIS_X2_1,
	CTRL_CMN_LENS_UNDIS_X2_2,
	CTRL_CMN_LENS_UNDIS_X2_3,
	CTRL_CMN_LENS_UNDIS_X1_0,
	CTRL_CMN_LENS_UNDIS_X1_1,
	CTRL_CMN_LENS_UNDIS_X1_2,
	CTRL_CMN_LENS_UNDIS_X1_3,
	CTRL_CMN_LENS_UNDIS_X0_0,
	CTRL_CMN_LENS_UNDIS_X0_1,
	CTRL_CMN_LENS_UNDIS_X0_2,
	CTRL_CMN_LENS_UNDIS_X0_3,
	CTRL_CMN_LENS_OPNCV_PARAM_CX_0,
	CTRL_CMN_LENS_OPNCV_PARAM_CX_1,
	CTRL_CMN_LENS_OPNCV_PARAM_CX_2,
	CTRL_CMN_LENS_OPNCV_PARAM_CX_3,
	CTRL_CMN_LENS_OPNCV_PARAM_CY_0,
	CTRL_CMN_LENS_OPNCV_PARAM_CY_1,
	CTRL_CMN_LENS_OPNCV_PARAM_CY_2,
	CTRL_CMN_LENS_OPNCV_PARAM_CY_3,
	CTRL_CMN_LENS_OPNCV_PARAM_FX_0,
	CTRL_CMN_LENS_OPNCV_PARAM_FX_1,
	CTRL_CMN_LENS_OPNCV_PARAM_FX_2,
	CTRL_CMN_LENS_OPNCV_PARAM_FX_3,
	CTRL_CMN_LENS_OPNCV_PARAM_FY_0,
	CTRL_CMN_LENS_OPNCV_PARAM_FY_1,
	CTRL_CMN_LENS_OPNCV_PARAM_FY_2,
	CTRL_CMN_LENS_OPNCV_PARAM_FY_3,
	CTRL_CMN_LENS_OPNCV_PARAM_K1_0,
	CTRL_CMN_LENS_OPNCV_PARAM_K1_1,
	CTRL_CMN_LENS_OPNCV_PARAM_K1_2,
	CTRL_CMN_LENS_OPNCV_PARAM_K1_3,
	CTRL_CMN_LENS_OPNCV_PARAM_K2_0,
	CTRL_CMN_LENS_OPNCV_PARAM_K2_1,
	CTRL_CMN_LENS_OPNCV_PARAM_K2_2,
	CTRL_CMN_LENS_OPNCV_PARAM_K2_3,
	CTRL_CMN_LENS_OPNCV_PARAM_P1_0,
	CTRL_CMN_LENS_OPNCV_PARAM_P1_1,
	CTRL_CMN_LENS_OPNCV_PARAM_P1_2,
	CTRL_CMN_LENS_OPNCV_PARAM_P1_3,
	CTRL_CMN_LENS_OPNCV_PARAM_P2_0,
	CTRL_CMN_LENS_OPNCV_PARAM_P2_1,
	CTRL_CMN_LENS_OPNCV_PARAM_P2_2,
	CTRL_CMN_LENS_OPNCV_PARAM_P2_3,
	CTRL_CMN_LENS_OPNCV_PARAM_K3_0,
	CTRL_CMN_LENS_OPNCV_PARAM_K3_1,
	CTRL_CMN_LENS_OPNCV_PARAM_K3_2,
	CTRL_CMN_LENS_OPNCV_PARAM_K3_3,
	CTRL_CMN_LENS_OPNCV_PARAM_K4_0,
	CTRL_CMN_LENS_OPNCV_PARAM_K4_1,
	CTRL_CMN_LENS_OPNCV_PARAM_K4_2,
	CTRL_CMN_LENS_OPNCV_PARAM_K4_3,
	CTRL_CMN_LENS_OPNCV_PARAM_K5_0,
	CTRL_CMN_LENS_OPNCV_PARAM_K5_1,
	CTRL_CMN_LENS_OPNCV_PARAM_K5_2,
	CTRL_CMN_LENS_OPNCV_PARAM_K5_3,
	CTRL_CMN_LENS_OPNCV_PARAM_K6_0,
	CTRL_CMN_LENS_OPNCV_PARAM_K6_1,
	CTRL_CMN_LENS_OPNCV_PARAM_K6_2,
	CTRL_CMN_LENS_OPNCV_PARAM_K6_3,

	CTRL_CMN_MAX
}eCTRL_CMN;

typedef enum _eCTRL_MODE{
	CTRL_MODE_TOF_MODE_FLAG,
	CTRL_MODE_LD_FLAG,
	CTRL_MODE_RANGE_NEAR_LIMIT,
	CTRL_MODE_RANGE_FAR_LIMIT,
	CTRL_MODE_DEPTH_UNIT,
	CTRL_MODE_EXP_MAX ,
	CTRL_MODE_EXP_DFLT,
	CTRL_MODE_AE_DIST1,
	CTRL_MODE_AE_EXP1,
	CTRL_MODE_AE_SLOPE1,
	CTRL_MODE_AE_OFST1,
	CTRL_MODE_AE_DIST2,
	CTRL_MODE_AE_EXP2,
	CTRL_MODE_AE_SLOPE2,
	CTRL_MODE_AE_OFST2,
	CTRL_MODE_AE_DIST3,
	CTRL_MODE_AE_EXP3,
	CTRL_MODE_AE_SLOPE3,
	CTRL_MODE_AE_OFST3,
	CTRL_MODE_VD_INI_OFST,
	CTRL_MODE_LD_PLS_DUTY,
	CTRL_MODE_VD_DURATION,
	CTRL_MODE_VD_REG_ADR,
	CTRL_MODE_NUM_CLK_IN_HD,
	CTRL_MODE_BETA_NUM,
	CTRL_MODE_NUM_HD_IN_READ,
	CTRL_MODE_CLK_WIDTH_U,
	CTRL_MODE_CLK_WIDTH_L,
	CTRL_MODE_TOF_EMT_PERI_OFST,
	CTRL_MODE_TOF_SEQ_INI_OFST,
	CTRL_MODE_LD_A0_WIN,
	CTRL_MODE_LD_A1_WIN,
	CTRL_MODE_LD_A2_WIN,
	CTRL_MODE_SUB_WIN,

	CTRL_MODE_MAX
}eCTRL_MODE;



/* base address */
#define ROM_CMN_BASE    (0x0000)
#define ROM_MODE0_BASE  (0x0390)
#define ROM_MODE1_BASE  (0x0600)
#define ROM_CS_INI_CODE_0            (0x0870)
#define ROM_CS_INI_CODE_END          (0x2000)
#define MAX_CS_INI_CODE_SIZE         (ROM_CS_INI_CODE_END - ROM_CS_INI_CODE_0)

/* offset address from ROM_CMN_BASE */
#define ROM_CAM_MODEL_NAME_0         (0x0000)
#define ROM_CS_MODEL_NAME_0         (0x0020)
#define ROM_TOFIS_MODEL_NAME_0       (0x0040)
#define ROM_LENS_MODEL_NAME_0        (0x0060)
#define ROM_CAM_SER_NO               (0x0080)
#define ROM_MAP_VERSION              (0x0082)
#define ROM_EX_CAM_SER_NO            (0x0084)
#define ROM_CALIB_DATE               (0x0086)
#define ROM_CALIB_SER_NO             (0x0088)
#define ROM_CAM_TYPE_CODE1           (0x008A)
#define ROM_CAM_TYPE_CODE2           (0x008C)
#define ROM_CS_MCODE_ID             (0x008E)
#define ROM_OPT_AXIS_CNTR_H          (0x0090)
#define ROM_OPT_AXIS_CNTR_V          (0x0092)
#define ROM_OPT_AXIS_TILT_ANGL       (0x0094)
#define ROM_OPT_AXIS_PAN_ANGL        (0x0096)
#define ROM_LENS_FOV_H               (0x0098)
#define ROM_LENS_FOV_V               (0x009A)
#define ROM_PRLX_H_FRM_RGBIS         (0x009C)
#define ROM_PRLX_V_FRM_RGBIS         (0x009E)
#define ROM_TOFIS_PITCH              (0x00A0)
#define ROM_FOCAL_LEN                (0x00A2)
#define ROM_VALID_RANG_MODE          (0x00A4)
#define ROM_DATA_PACK_STR            (0x00A6)
#define ROM_TAL_MODE_FLAG            (0x00A8)
#define ROM_CS_INI_CODE_SIZE        (0x00AA)
#define ROM_CHECK_SUM                (0x00AC)


#define ROM_DEPTH_PLNR_X3_0         (0x00B0)
#define ROM_DEPTH_PLNR_X2_0         (0x00B8)
#define ROM_DEPTH_PLNR_X1_0         (0x00C0)
#define ROM_DEPTH_PLNR_X0_0         (0x00C8)
#define ROM_LENS_UNDIS_X3_0         (0x00D0)
#define ROM_LENS_UNDIS_X2_0         (0x00D8)
#define ROM_LENS_UNDIS_X1_0         (0x00E0)
#define ROM_LENS_UNDIS_X0_0         (0x00E8)
#define ROM_LENS_OPNCV_PARAM_CX_0   (0x00F0)
#define ROM_LENS_OPNCV_PARAM_CY_0   (0x00F8)
#define ROM_LENS_OPNCV_PARAM_FX_0   (0x0100)
#define ROM_LENS_OPNCV_PARAM_FY_0   (0x0108)
#define ROM_LENS_OPNCV_PARAM_K1_0   (0x0110)
#define ROM_LENS_OPNCV_PARAM_K2_0   (0x0118)
#define ROM_LENS_OPNCV_PARAM_P1_0   (0x0120)
#define ROM_LENS_OPNCV_PARAM_P2_0   (0x0128)
#define ROM_LENS_OPNCV_PARAM_K3_0   (0x0130)
#define ROM_LENS_OPNCV_PARAM_K4_0   (0x0138)
#define ROM_LENS_OPNCV_PARAM_K5_0   (0x0140)
#define ROM_LENS_OPNCV_PARAM_K6_0   (0x0148)

#define ROM_SHD_OFST0                (0x0150)

#define ROM_SHD                      (0x02D0)
#define ROM_SHD_X0                   (0x02D2)
#define ROM_SHD_XPWR0                (0x02D4)
#define ROM_SHD_XPWR1                (0x02D6)
#define ROM_SHD_XPWR2                (0x02D8)
#define ROM_SHD_XPWR3                (0x02DA)
#define ROM_SHD_Y0                   (0x02DC)
#define ROM_SHD_YPWR0                (0x02DE)
#define ROM_SHD_YPWR1                (0x02E0)
#define ROM_SHD_YPWR2                (0x02E2)

#define ROM_DFCT_PIX_TH_TBL0         (0x02F0)
#define ROM_DFCT_PIX_TH_TBL1         (0x02F2)
#define ROM_DFCT_PIX_TH_TBL2         (0x02F4)
#define ROM_DFCT_PIX_TH_TBL3         (0x02F6)
#define ROM_DFCT_PIX_TH_TBL4         (0x02F8)
#define ROM_DFCT_PIX_TH_TBL5         (0x02FA)
#define ROM_DFCT_PIX_TH_TBL6         (0x02FC)
#define ROM_DFCT_PIX_TH_TBL7         (0x02FE)
#define ROM_DFCT_PIX_TH_TBL8         (0x0300)
#define ROM_DFCT_PIX_TH_TBL9         (0x0302)
#define ROM_DFCT_PIX_TH_TBL10        (0x0304)
#define ROM_DFCT_PIX_TH_TBL11        (0x0306)
#define ROM_DFCT0                    (0x0308)
#define ROM_DFCT1                    (0x030A)
#define ROM_SHP_LOC                  (0x030C)
#define ROM_SHD_LOC                  (0x030E)
#define ROM_OUTPUT                   (0x0310)
#define ROM_OUTPUTSEL                (0x0312)
#define ROM_VC                       (0x0314)

#define ROM_GRID3                    (0x0320)
#define ROM_IR1                      (0x0322)
#define ROM_IR_GMM0                  (0x0324)
#define ROM_IR_GMM1                  (0x0326)
#define ROM_IR_GMM2                  (0x0328)
#define ROM_IR_GMM_Y0                (0x032A)
#define ROM_IR_GMM_Y1                (0x032C)
#define ROM_IR_GMM_Y2                (0x032E)
#define ROM_IR_GMM_Y3                (0x0330)
#define ROM_IR_GMM_Y4                (0x0332)
#define ROM_IR_GMM_Y5                (0x0334)
#define ROM_IR_GMM_Y6                (0x0336)
#define ROM_IR_GMM_Y7                (0x0338)
#define ROM_IR_GMM_Y8                (0x033A)
#define ROM_CHKR_UPPRTH              (0x033C)
#define ROM_CHKR_LWRTH               (0x033E)
#define ROM_CHKR_START_V             (0x0340)
#define ROM_CHKR_START_H             (0x0342)
#define ROM_CHKR_SIZE_H              (0x0344)
#define ROM_CHKR_UPPRERR_H           (0x0346)
#define ROM_CHKR_UPPRERR_V           (0x0348)
#define ROM_CHKR_LWRERR_H            (0x034A)
#define ROM_CHKR_LWRERR_V            (0x034C)
#define ROM_CHKR_DET_ENA             (0x034E)


/* offset address from ROM_MODEn_BASE */
#define ROM_TOF_MODE_FLAG            (0x0000)
#define ROM_LD_FLAG                  (0x0002)
#define ROM_RANGE_NEAR_LIMIT         (0x0004)
#define ROM_RANGE_FAR_LIMIT          (0x0006)
#define ROM_DEPTH_UNIT               (0x0008)

#define ROM_EXP_MAX                  (0x000C)
#define ROM_EXP_DFLT                 (0x000E)
#define ROM_AE_DIST1                 (0x0010)
#define ROM_AE_EXP1                  (0x0012)
#define ROM_AE_SLOPE1                (0x0014)
#define ROM_AE_OFST1                 (0x0016)
#define ROM_AE_DIST2                 (0x0018)
#define ROM_AE_EXP2                  (0x001A)
#define ROM_AE_SLOPE2                (0x001C)
#define ROM_AE_OFST2                 (0x001E)
#define ROM_AE_DIST3                 (0x0020)
#define ROM_AE_EXP3                  (0x0022)
#define ROM_AE_SLOPE3                (0x0024)
#define ROM_AE_OFST3                 (0x0026)

#define ROM_EXP_ADR_NUM              (0x0040)
#define ROM_EXP_ADR_LONG1            (0x0042)
#define ROM_EXP_ADR_LONG2            (0x0044)
#define ROM_EXP_ADR_LONG3            (0x0046)
#define ROM_EXP_ADR_LONG4            (0x0048)
#define ROM_EXP_ADR_LONG5            (0x004A)
#define ROM_EXP_ADR_LONG6            (0x004C)
#define ROM_EXP_ADR_LONG7            (0x004E)
#define ROM_EXP_ADR_LONG8            (0x0050)
#define ROM_EXP_ADR_LONG9            (0x0052)
#define ROM_EXP_ADR_LONG10           (0x0054)
#define ROM_EXP_ADR_LONG11           (0x0056)
#define ROM_EXP_ADR_LONG12           (0x0058)
#define ROM_EXP_ADR_LONG13           (0x005A)
#define ROM_EXP_ADR_LONG14           (0x005C)
#define ROM_EXP_ADR_LONG15           (0x005E)
#define ROM_EXP_ADR_SHORT1           (0x0060)
#define ROM_EXP_ADR_SHORT2           (0x0062)
#define ROM_EXP_ADR_SHORT3           (0x0064)
#define ROM_EXP_ADR_SHORT4           (0x0066)
#define ROM_EXP_ADR_LMS1             (0x0068)
#define ROM_EXP_ADR_LMS2             (0x006A)
#define ROM_EXP_ADR_LMS3             (0x006C)
#define ROM_EXP_ADR_LMS4             (0x006E)
#define ROM_DMMY_TRNS_NUM            (0x0070)
#define ROM_DMMY_TRNS_ADR1           (0x0072)
#define ROM_DMMY_TRNS_ADR2           (0x0074)
#define ROM_DMMY_TRNS_ADR3           (0x0076)
#define ROM_DMMY_TRNS_ADR4           (0x0078)
#define ROM_VD_INI_OFST              (0x007A)
#define ROM_VD_INI_OFST_ADR_NUM      (0x007C)
#define ROM_VD_INIT_OFST_ADR1        (0x007E)
#define ROM_VD_INIT_OFST_ADR2        (0x0080)
#define ROM_VD_INIT_OFST_ADR3        (0x0082)
#define ROM_VD_INIT_OFST_ADR4        (0x0084)
#define ROM_LD_PLS_DUTY              (0x0086)
#define ROM_VD_DURATION              (0x0088)
#define ROM_VD_REG_ADR               (0x008A)
#define ROM_NUM_CLK_IN_HD            (0x008C)
#define ROM_BETA_NUM                 (0x008E)
#define ROM_NUM_HD_IN_READ           (0x0090)
#define ROM_CLK_WIDTH_U              (0x0092)
#define ROM_CLK_WIDTH_L              (0x0094)
#define ROM_TOF_EMT_PERI_OFST        (0x0096)
#define ROM_TOF_SEQ_INI_OFST         (0x0098)

#define ROM_LD_A0_WIN                (0x00A0)
#define ROM_LD_A1_WIN                (0x00A2)
#define ROM_LD_A2_WIN                (0x00A4)
#define ROM_SUB_WIN                  (0x00A6)
#define ROM_PHASE_ADR_NUM            (0x00A8)

#define ROM_PHASE_SUB_1              (0x00B0)
#define ROM_PHASE_SUB_2              (0x00B2)
#define ROM_PHASE_SUB_3              (0x00B4)
#define ROM_PHASE_SUB_4              (0x00B6)
#define ROM_PHASE_SUB_5              (0x00B8)
#define ROM_PHASE_SUB_6              (0x00BA)
#define ROM_PHASE_SUB_7              (0x00BC)
#define ROM_PHASE_SUB_8              (0x00BE)
#define ROM_PHASE_A0_1               (0x00C0)
#define ROM_PHASE_A0_2               (0x00C2)
#define ROM_PHASE_A0_3               (0x00C4)
#define ROM_PHASE_A0_4               (0x00C6)
#define ROM_PHASE_A0_5               (0x00C8)
#define ROM_PHASE_A0_6               (0x00CA)
#define ROM_PHASE_A0_7               (0x00CC)
#define ROM_PHASE_A0_8               (0x00CE)
#define ROM_PHASE_A1_1               (0x00D0)
#define ROM_PHASE_A1_2               (0x00D2)
#define ROM_PHASE_A1_3               (0x00D4)
#define ROM_PHASE_A1_4               (0x00D6)
#define ROM_PHASE_A1_5               (0x00D8)
#define ROM_PHASE_A1_6               (0x00DA)
#define ROM_PHASE_A1_7               (0x00DC)
#define ROM_PHASE_A1_8               (0x00DE)
#define ROM_PHASE_A2_1               (0x00E0)
#define ROM_PHASE_A2_2               (0x00E2)
#define ROM_PHASE_A2_3               (0x00E4)
#define ROM_PHASE_A2_4               (0x00E6)
#define ROM_PHASE_A2_5               (0x00E8)
#define ROM_PHASE_A2_6               (0x00EA)
#define ROM_PHASE_A2_7               (0x00EC)
#define ROM_PHASE_A2_8               (0x00EE)

#define ROM_LNR_OFST00               (0x00F0)

#define ROM_LNR_X0                   (0x0152)
#define ROM_LNR_XPWR_01              (0x0154)
#define ROM_LNR_XPWR_05              (0x0156)
#define ROM_LNR_XPWR_09              (0x0158)
#define ROM_LNR_XPWR_13              (0x015A)
#define ROM_LNR_XPWR_17              (0x015C)
#define ROM_LNR_XPWR_21              (0x015E)
#define ROM_LNR_XPWR_25              (0x0160)
#define ROM_LNR_XPWR_29              (0x0162)
#define ROM_LNR_XPWR_33              (0x0164)
#define ROM_LNR_XPWR_37              (0x0166)
#define ROM_LNR_XPWR_41              (0x0168)
#define ROM_LNR_XPWR_45              (0x016A)

#define ROM_DEPTH_OFST               (0x0170)
#define ROM_DEPTH_EX_OFST            (0x0172)
#define ROM_DEPTH_SLOPE              (0x0174)
#define ROM_IDLE_PERI_NUM            (0x0176)
#define ROM_IDLE_PERI_ADR1           (0x0178)
#define ROM_IDLE_PERI_ADR2           (0x017A)
#define ROM_IDLE_PERI_ADR3           (0x017C)
#define ROM_IDLE_PERI_ADR4           (0x017E)
#define ROM_RATE_ADJST0              (0x0180)
#define ROM_RATE_ADJST1              (0x0182)
#define ROM_RATE_ADJST2              (0x0184)
#define ROM_ALIGN0                   (0x0186)
#define ROM_ALIGN1                   (0x0188)
#define ROM_ALIGN2                   (0x018A)
#define ROM_ALIGN3                   (0x018C)
#define ROM_ALIGN4                   (0x018E)
#define ROM_ALIGN5                   (0x0190)
#define ROM_ALIGN6                   (0x0192)
#define ROM_ALIGN7                   (0x0194)
#define ROM_ALIGN8                   (0x0196)
#define ROM_ALIGN9                   (0x0198)
#define ROM_ALIGN10                  (0x019A)
#define ROM_READ_SIZE0               (0x019C)
#define ROM_READ_SIZE1               (0x019E)
#define ROM_READ_SIZE3               (0x01A0)
#define ROM_READ_SIZE4               (0x01A2)
#define ROM_READ_SIZE5               (0x01A4)
#define ROM_READ_SIZE6               (0x01A6)
#define ROM_READ_SIZE7               (0x01A8)
#define ROM_ROI0                     (0x01AA)
#define ROM_ROI1                     (0x01AC)
#define ROM_ROI2                     (0x01AE)
#define ROM_ROI3                     (0x01B0)
#define ROM_ROI4                     (0x01B2)
#define ROM_ROI5                     (0x01B4)
#define ROM_ROI6                     (0x01B6)
#define ROM_ROI7                     (0x01B8)
#define ROM_IR_LNR12_SW              (0x01BA)


#define ROM_GRID0                    (0x01C0)
#define ROM_GRID1                    (0x01C2)
#define ROM_GRID2                    (0x01C4)
#define ROM_RAWNR_XPWR_1             (0x01C6)
#define ROM_RAWNR_XPWR_5             (0x01C8)
#define ROM_RAWNR_XPWR_9             (0x01CA)
#define ROM_RAWNR_BL_TBL00           (0x01CC)
#define ROM_RAWNR_BL_TBL01           (0x01CE)
#define ROM_RAWNR_BL_TBL02           (0x01D0)
#define ROM_RAWNR_BL_TBL03           (0x01D2)
#define ROM_RAWNR_BL_TBL04           (0x01D4)
#define ROM_RAWNR_BL_TBL05           (0x01D6)
#define ROM_RAWNR_BL_TBL06           (0x01D8)
#define ROM_RAWNR_BL_TBL07           (0x01DA)
#define ROM_RAWNR_BL_TBL08           (0x01DC)
#define ROM_RAWNR_BL_TBL09           (0x01DE)
#define ROM_RAWNR_BL_TBL10           (0x01E0)
#define ROM_RAWNR_BL_TBL11           (0x01E2)
#define ROM_RAWNR_BL_TBL12           (0x01E4)
#define ROM_RAWNR_MED                (0x01E6)
#define ROM_RAWNR_SAT_TH             (0x01E8)
#define ROM_RAWNR_BK_TBL00           (0x01EA)
#define ROM_RAWNR_BK_TBL01           (0x01EC)
#define ROM_RAWNR_BK_TBL02           (0x01EE)
#define ROM_RAWNR_BK_TBL03           (0x01F0)
#define ROM_RAWNR_BK_TBL04           (0x01F2)
#define ROM_RAWNR_BK_TBL05           (0x01F4)
#define ROM_RAWNR_BK_TBL06           (0x01F6)
#define ROM_RAWNR_BK_TBL07           (0x01F8)
#define ROM_RAWNR_BK_TBL08           (0x01FA)
#define ROM_RAWNR_BK_TBL09           (0x01FC)
#define ROM_RAWNR_BK_TBL10           (0x01FE)
#define ROM_RAWNR_BK_TBL11           (0x0200)
#define ROM_RAWNR_BK_TBL12           (0x0202)
#define ROM_COR0                     (0x0204)
#define ROM_COR1                     (0x0206)
#define ROM_COR2                     (0x0208)
#define ROM_CORB0                    (0x020A)
#define ROM_CORB1                    (0x020C)
#define ROM_CORB2                    (0x020E)
#define ROM_CORF0                    (0x0210)
#define ROM_CORF1                    (0x0212)
#define ROM_CORF2                    (0x0214)
#define ROM_IR_ENABLED_COR           (0x0216)
#define ROM_DEPTH1                   (0x0218)
#define ROM_CONTROL                  (0x021A)
#define ROM_PLS_MOD_CTRL             (0x021C)
#define ROM_PLS_MOD_VAL0             (0x021E)
#define ROM_PLS_MOD_VAL1             (0x0220)
#define ROM_PLS_MOD_VAL2             (0x0222)
#define ROM_PLS_MOD_VAL3             (0x0224)
#define ROM_PLS_MOD_VAL4             (0x0226)
#define ROM_PLS_MOD_VAL5             (0x0228)
#define ROM_PLS_MOD_VAL6             (0x022A)
#define ROM_PLS_MOD_VAL7             (0x022C)
#define ROM_PLS_MOD_VAL8             (0x022E)
#define ROM_PLS_MOD_VAL9             (0x0230)
#define ROM_DEPTH_ALF_GAIN           (0x0232)
#define ROM_DEPTH_ALF_OFST           (0x0234)
#define ROM_DPTHDET_START_H          (0x0236)
#define ROM_DPTHDET_START_V          (0x0238)
#define ROM_DPTHDET_SIZE_H           (0x023A)
#define ROM_DPTHDET_SIZE_V           (0x023C)



/**************************************************************************************
 * ADDI9033 registers for TOF signal processing.
 * These values are calibrated in advance and assumed to be stored in EEPROM/FLASH-ROM.
 **************************************************************************************/
/* common registers */
extern uint16_t gunIspRegCmn[][2];

/* registers for each range mode */
extern uint16_t gunIspRegMode[2][ISP_REG_MODE_MAX][2];

/* registers for each range mode (CS ram register) */
extern uint16_t gunIspRamMode[2][ISP_RAM_MODE_MAX];

/* size of variables */
extern uint32_t gunIspRegCmn_Size;
extern uint32_t gunIspRegMode0_Size;
extern uint32_t gunIspRegMode1_Size;

extern uint32_t gunIspRamMode0_Size;
extern uint32_t gunIspRamMode1_Size;

/* EEPROM data for each range mode(not have CS register) */
extern uint16_t gunCtrlCmn[CTRL_CMN_MAX];
extern uint16_t gunCtrlMode[2][CTRL_MODE_MAX];

#endif /* __TOF_ISP_TABLE_H__ */
